### ISSUE TITLE
コード内部のオーバフローに背景がつかない

### ISSUE THREAD

**Issue by curegit** [prog-g/prog-g.github.io#36]
## 今の状態

記事にコードを貼ったとき、長い行があれば x 方向のはみ出しが発生しスクロールバーがつく。
しかし、はみ出した部分に白い背景が付与されない。

![screenshot from 2018-10-20 18-41-05](https://user-images.githubusercontent.com/37978051/47266449-c2bd3280-d571-11e8-8b39-167961fa64f1.png)

## こうあるべき
右端まで白の背景がある

### 環境
- Ubuntu 18.04 LTS (Firefox)
- Windows7 SP1 (Chrome 69.0.3497.100)

**Comment by ahuglajbclajep** [comment]
元にしているテーマ [slate](https://github.com/pages-themes/slate) の問題な気がする。
[slate のデモページ](https://pages-themes.github.io/slate/) でも同様の現象が見られる。
![image](https://user-images.githubusercontent.com/25224365/47266696-36ad0a00-d575-11e8-8b1b-4c42cf05c9cb.png)

**Comment by ahuglajbclajep** [comment]
おそらくこのあたり
https://github.com/pages-themes/slate/blob/52dc232fc58e5cfac2355ad81569659c0726c696/_sass/jekyll-theme-slate.scss#L157-L179

**Comment by curegit** [comment]
`code` 要素か `pre code` セレクタで `overflow: auto` を与えるのが楽に治せそう

**Comment by curegit** [comment]
これはslateにissue立てた方がいいのかな

**Comment by ahuglajbclajep** [comment]
とりあえずはここのについて直すPR出して、様子見て大丈夫そうならissueなりPRを立てたほうがよさそう？

**Comment by curegit** [comment]
それがよさそう :+1: 
そのうちPR立てます
