### ISSUE TITLE
引用部分が textlint に引っ掛かると困る

### ISSUE THREAD

**Issue by curegit** [prog-g/prog-g.github.io#40]
## 今の状態
引用部分、事実として変えられない文字列が textlint に引っ掛かると対処できない

![quote](https://user-images.githubusercontent.com/37978051/47959439-69e8a200-e027-11e8-9e22-d9536a02613c.png)

よって #34 が textlint をパスしない状態で放置している

## こうあるべき
- 引用部分を無視するなどのルールが必要
- #34 が textlint をパスするようにする

## その他
- textlint が更新されるかもしれないので保留中

## 関連
- textlint-ja/textlint-rule-ja-no-redundant-expression#5

**Comment by ahuglajbclajep** [comment]
3.xで修正されたため閉じておきます。
https://github.com/textlint-ja/textlint-rule-ja-no-redundant-expression/releases/tag/3.0.0
