### ISSUE TITLE
Google Slideのモバイルレイアウトの崩壊

### ISSUE THREAD

**Issue by curegit** [prog-g/prog-g.github.io#7]
## 今の状態
スマートフォンのブラウザから[該当ページ](https://prog-g.github.io/2018/04/12/%E7%AC%AC1%E5%9B%9ELT.html)にあるGoogle Slideの下部のスライド選択メニューを開くとレイアウトが崩れる  

![ios1](https://user-images.githubusercontent.com/37978051/38737283-b6c9031c-3f69-11e8-8d38-8f4e30d45587.png)

## こうあるべき
メニューを開いてもフレームがラッパーからはみ出さないようにする

### 環境
- OSとそのバージョン:  iPhone SE/iOS 11.3
- ブラウザとそのバージョン:  Safari 11.0

**Comment by ahuglajbclajep** [comment]
この問題を修正するには、Googleスライドの埋め込みリンクをその都度divで囲む必要があると思われます  
スライドを貼るハードルも上がりますし、Safari限定で起きるという点も踏まえ、この問題は対応しないことにします
