### ISSUE TITLE
title要素がない

### ISSUE THREAD

**Issue by curegit** [prog-g/prog-g.github.io#9]
## 今の状態
head内にtitle要素がない
f66b9230fe4afa2a27a4e2596fec51cc2e63bea3 で削除された？

## こうあるべき
title要素は欲しい

### 環境
- OSとそのバージョン:  Win7 home SP1
- ブラウザとそのバージョン:  Chrome 65.0.3325.181 x64

**Comment by ahuglajbclajep** [comment]
気付かなかった……
ありがと〜 :smile:
